server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: picture-hub
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 5MB
  # session 配置
  session:
    store-type: redis
    # session 30 天过期
    timeout: 2592000


