server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: picture-hub
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 5MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "pic-hub接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - org.zepe.pichub.controller
